M48
; DRILL file {KiCad (6.0.2)} date Thu Mar 10 14:49:58 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-10T14:49:58-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X44.67Y-37.177
X44.67Y-104.487
X85.31Y-37.177
X85.31Y-104.487
T0
M30
