M48
; DRILL file {KiCad (6.0.2)} date Wed Mar  2 22:35:28 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-02T22:35:28-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X44.655Y-37.258
X44.655Y-105.0
X85.2Y-105.0
X85.305Y-37.258
T0
M30
